src/Entity/Organisation.php
<?php

namespace App\Entity;

use App\Repository\OrganisationRepository;
use Doctrine\ORM\Mapping as ORM;
use App\Entity\User;

/**
 * @ORM\Entity(repositoryClass=OrganisationRepository::class)
 */
class Organisation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $denomination;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $sigle;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $statut_juridique;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="date")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_recepicee;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $province;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $objet_social;

    /**
     * @ORM\Column(type="text")
     */
    private $description_activite;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $site_internet;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lien_facebook;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $numero_telephone2;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email_organisation;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_telephone1;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="organisation",cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDenomination(): ?string
    {
        return $this->denomination;
    }

    public function setDenomination(string $denomination): self
    {
        $this->denomination = $denomination;

        return $this;
    }

    public function getSigle(): ?string
    {
        return $this->sigle;
    }

    public function setSigle(string $sigle): self
    {
        $this->sigle = $sigle;

        return $this;
    }

    public function getStatutJuridique(): ?string
    {
        return $this->statut_juridique;
    }

    public function setStatutJuridique(string $statut_juridique): self
    {
        $this->statut_juridique = $statut_juridique;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getNumeroRecepicee(): ?string
    {
        return $this->numero_recepicee;
    }

    public function setNumeroRecepicee(string $numero_recepicee): self
    {
        $this->numero_recepicee = $numero_recepicee;

        return $this;
    }

    public function getProvince(): ?string
    {
        return $this->province;
    }

    public function setProvince(string $province): self
    {
        $this->province = $province;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {
        $this->ville = $ville;

        return $this;
    }

    public function getObjetSocial(): ?string
    {
        return $this->objet_social;
    }

    public function setObjetSocial(string $objet_social): self
    {
        $this->objet_social = $objet_social;

        return $this;
    }

    public function getDescriptionActivite(): ?string
    {
        return $this->description_activite;
    }

    public function setDescriptionActivite(string $description_activite): self
    {
        $this->description_activite = $description_activite;

        return $this;
    }

    public function getSiteInternet(): ?string
    {
        return $this->site_internet;
    }

    public function setSiteInternet(?string $site_internet): self
    {
        $this->site_internet = $site_internet;

        return $this;
    }

    public function getLienFacebook(): ?string
    {
        return $this->lien_facebook;
    }

    public function setLienFacebook(?string $lien_facebook): self
    {
        $this->lien_facebook = $lien_facebook;

        return $this;
    }

    public function getNumeroTelephone2(): ?string
    {
        return $this->numero_telephone2;
    }

    public function setNumeroTelephone2(?string $numero_telephone2): self
    {
        $this->numero_telephone2 = $numero_telephone2;

        return $this;
    }

    public function getEmailOrganisation(): ?string
    {
        return $this->email_organisation;
    }

    public function setEmailOrganisation(?string $email_organisation): self
    {
        $this->email_organisation = $email_organisation;

        return $this;
    }

    public function getNumeroTelephone1(): ?string
    {
        return $this->numero_telephone1;
    }

    public function setNumeroTelephone1(string $numero_telephone1): self
    {
        $this->numero_telephone1 = $numero_telephone1;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    
}

src/Form/OrganisationType.php
<?php

namespace App\Form;

use App\Entity\Organisation;
use App\Entity\User;
use App\Repository\UserRepository;
use Doctrine\ORM\QueryBuilder;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrganisationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('denomination')
            ->add('sigle')
            ->add('statut_juridique')
            ->add('adresse')
            ->add('createdAt')
            ->add('numero_recepicee')
            ->add('province')
            ->add('ville')
            ->add('objet_social')
            ->add('description_activite')
            ->add('site_internet')
            ->add('lien_facebook')
            ->add('numero_telephone1')
            ->add('numero_telephone2')
            ->add('email_organisation')
            // ->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Organisation::class,
        ]);
    }
}

src/Controller/OrganisationController.php
<?php

namespace App\Controller;

use App\Entity\Organisation;
use App\Entity\User;
use App\Form\OrganisationType;
use App\Repository\OrganisationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/organisation")
 */
class OrganisationController extends AbstractController
{
    /**
     * @Route("/", name="organisation_index", methods={"GET"})
     */
    public function index(OrganisationRepository $organisationRepository): Response
    {
        return $this->render('organisation/index.html.twig', [
            'organisations' => $organisationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="organisation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $organisation = new Organisation();
        $form = $this->createForm(OrganisationType::class, $organisation);
        
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //Récupération de l'utilisateur.
            $organisation->setUser($this->getUser());
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($organisation);
            $entityManager->flush();

            return $this->redirectToRoute('account');
        }

        return $this->render('organisation/new.html.twig', [
            'organisation' => $organisation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="organisation_show", methods={"GET"})
     */
    public function show(Organisation $organisation): Response
    {
        return $this->render('organisation/show.html.twig', [
            'organisation' => $organisation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="organisation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Organisation $organisation): Response
    {
        $form = $this->createForm(OrganisationType::class, $organisation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('organisation_index');
        }

        return $this->render('organisation/edit.html.twig', [
            'organisation' => $organisation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="organisation_delete", methods={"POST"})
     */
    public function delete(Request $request, Organisation $organisation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$organisation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($organisation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('organisation_index');
    }
}

templates/organisation/_delete_form.html.twig
<form method="post" action="{{ path('organisation_delete', {'id': organisation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ organisation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/organisation/_form.html.twig
{# Zone du formulaire #}
<div class="row">
  <div class="mx-auto">
    <div class="ts-grid-box" id="ts-grid-box">

      <p class="text-left pt-2 pb-1 blue-color">Tous les champs sont obligatoires (*)</p>
      <div class="card">
        <div class="card-body">
          <h5 class="card-title log-sign-title mb-25 blue-color text-center">Informations liées à votre organisation</h5>
          <!--Zone où j'insère les champs du formulaire-->
          {{ form_start(form) }}
          {{ form_widget(form) }}
          <div class="form-group text-center links">
          <button type="submit" class="btn btn-primary">{{ button_label|default('Ajouter') }}</button>
          </div>
          {{ form_end(form) }}
        </div>
      </div>
    </div>
    <!-- grid box end -->
  </div>
</div>

templates/organisation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Organisation{% endblock %}

{% block body %}
    <h1>Edit Organisation</h1>

    {{ include('organisation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('organisation_index') }}">back to list</a>

    {{ include('organisation/_delete_form.html.twig') }}
{% endblock %}

templates/organisation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Organisation index{% endblock %}

{% block body %}
    <h1>Organisation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Denomination</th>
                <th>Sigle</th>
                <th>Statut_juridique</th>
                <th>Adresse</th>
                <th>CreatedAt</th>
                <th>Numero_recepicee</th>
                <th>Province</th>
                <th>Ville</th>
                <th>Objet_social</th>
                <th>Description_activite</th>
                <th>Site_internet</th>
                <th>Lien_facebook</th>
                <th>Numero_telephone2</th>
                <th>Email_organisation</th>
                <th>Numero_telephone1</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for organisation in organisations %}
            <tr>
                <td>{{ organisation.id }}</td>
                <td>{{ organisation.denomination }}</td>
                <td>{{ organisation.sigle }}</td>
                <td>{{ organisation.statutJuridique }}</td>
                <td>{{ organisation.adresse }}</td>
                <td>{{ organisation.createdAt ? organisation.createdAt|date('Y-m-d') : '' }}</td>
                <td>{{ organisation.numeroRecepicee }}</td>
                <td>{{ organisation.province }}</td>
                <td>{{ organisation.ville }}</td>
                <td>{{ organisation.objetSocial }}</td>
                <td>{{ organisation.descriptionActivite }}</td>
                <td>{{ organisation.siteInternet }}</td>
                <td>{{ organisation.lienFacebook }}</td>
                <td>{{ organisation.numeroTelephone2 }}</td>
                <td>{{ organisation.emailOrganisation }}</td>
                <td>{{ organisation.numeroTelephone1 }}</td>
                <td>
                    <a href="{{ path('organisation_show', {'id': organisation.id}) }}">show</a>
                    <a href="{{ path('organisation_edit', {'id': organisation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="17">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('organisation_new') }}">Create new</a>
{% endblock %}

templates/organisation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Organisation{% endblock %}

{% block body %}
  <h6 class="log-sign-title mb-25 blue-color text-center h1">
    J'enregistre mon organisation
    <i class="fa fa-edit blue-color" aria-hidden="true"></i>
  </h6>

  {{ include('organisation/_form.html.twig') }}

  {# <a href="{{ path('organisation_index') }}">back to list</a> #}
{% endblock %}

templates/organisation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Organisation{% endblock %}

{% block body %}
    <h1>Organisation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ organisation.id }}</td>
            </tr>
            <tr>
                <th>Denomination</th>
                <td>{{ organisation.denomination }}</td>
            </tr>
            <tr>
                <th>Sigle</th>
                <td>{{ organisation.sigle }}</td>
            </tr>
            <tr>
                <th>Statut_juridique</th>
                <td>{{ organisation.statutJuridique }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ organisation.adresse }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ organisation.createdAt ? organisation.createdAt|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Numero_recepicee</th>
                <td>{{ organisation.numeroRecepicee }}</td>
            </tr>
            <tr>
                <th>Province</th>
                <td>{{ organisation.province }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ organisation.ville }}</td>
            </tr>
            <tr>
                <th>Objet_social</th>
                <td>{{ organisation.objetSocial }}</td>
            </tr>
            <tr>
                <th>Description_activite</th>
                <td>{{ organisation.descriptionActivite }}</td>
            </tr>
            <tr>
                <th>Site_internet</th>
                <td>{{ organisation.siteInternet }}</td>
            </tr>
            <tr>
                <th>Lien_facebook</th>
                <td>{{ organisation.lienFacebook }}</td>
            </tr>
            <tr>
                <th>Numero_telephone2</th>
                <td>{{ organisation.numeroTelephone2 }}</td>
            </tr>
            <tr>
                <th>Email_organisation</th>
                <td>{{ organisation.emailOrganisation }}</td>
            </tr>
            <tr>
                <th>Numero_telephone1</th>
                <td>{{ organisation.numeroTelephone1 }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('organisation_index') }}">back to list</a>

    <a href="{{ path('organisation_edit', {'id': organisation.id}) }}">edit</a>

    {{ include('organisation/_delete_form.html.twig') }}
{% endblock %}